spring:
  main:
    banner-mode: "off"
  profiles:
    include:
      - oidc
      - apimap
      - database
      - documentation
logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: INFO
server:
  address: 0.0.0.0
  port: 8081
  forward-headers-strategy: NATIVE
  error:
    include-stacktrace: never
    include-message: never
    include-exception: false
    whitelabel:
      enabled: false
